Major UI update and start of numerical analysis functionality
DIYSpectroid/SpecLight-App pull request #15
Opened 2022-08-11 11:45 UTC by user17359

2022-08-11 22:14 UTC, HulekJakub requested changes
Please read through my review. It would be beneficial to make a separate directory for UI pages

2022-08-11 22:14 UTC, HulekJakub commented on lib/overview.dart
> +                  }
I see this pattern very often. Wouldn't it be better for a utility class to contain this?

2022-08-11 22:14 UTC, HulekJakub commented on lib/numerical_analysis/find_peaks.dart
> +            }
Maybe `referenceY = min(referenceY, dataConverted[j].);`

2022-08-11 22:14 UTC, HulekJakub commented on lib/numerical_analysis/find_peaks.dart
> +            }
Maybe `referenceY = min(referenceY, dataConverted[j].);`

2022-08-11 22:14 UTC, HulekJakub commented on lib/numerical_analysis/find_peaks.dart
> +            }
^^

2022-08-11 22:14 UTC, HulekJakub commented on lib/numerical_analysis/find_peaks.dart
> +          }
Wouldn't `referenceY = max(rightMinimum, leftMinimum)`  be better? max function is available in dart:math

2022-08-11 22:14 UTC, HulekJakub commented on lib/numerical_analysis/find_peaks.dart
> +            }
I think 
`if(dataConverted[j].y >= dataConverted[i].y){
      hit = true;
 }`
is enough, loop will end either way, no need to set hit = true

2022-08-11 22:14 UTC, HulekJakub commented on lib/numerical_analysis/find_peaks.dart
> +            }
Maybe `referenceY = min(referenceY, dataConverted[j].);`

2022-08-11 22:14 UTC, HulekJakub commented on lib/numerical_analysis/find_peaks.dart
> +      if(i == 0){
Could we add one LinearData at the start and one at the end, both with value of 0 and just get rid of those ifs? Just one `for(int i = 1; i < data.length - ;i++){[...]} `

2022-08-11 22:16 UTC, HulekJakub commented
A small question. Shouldn't peak analysis have a separate branch?

2022-08-12 10:07 UTC, user17359 commented
>A small question. Shouldn't peak analysis have a separate branch?
It does, but merge was needed to create UI for that part of app.

2022-08-12 12:40 UTC, HulekJakub approved these changes
Okay

2023-05-21 19:00 UTC, merged